"""empty message

Revision ID: 52920e2bed61
Revises: 4dc505097156
Create Date: 2023-11-03 23:42:02.926159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52920e2bed61'
down_revision = '4dc505097156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desc', sa.String(length=3000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('desc')

    # ### end Alembic commands ###
